name: doctor_ranking
channels:
  - defaults
dependencies:
  - pip=19.2.2
  - python=3.7.4
  - pytest=5.0.1
  - mock=3.0.5
  - psycopy2=2.7.6.1
  - sqlalchemy=1.3.7
  - pandas=0.25.1
  - pip:
    - awscli
